"""initial migration

Revision ID: b87aa234c15f
Revises: 4628d2d25f7d
Create Date: 2022-07-28 23:05:09.954374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87aa234c15f'
down_revision = '4628d2d25f7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
